---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: casse-boubou/ha-addon-workflows/.github/workflows/pr-labels.yaml@a282ba79666926dfbfba02cf92390ae73832f0fc  # main
