---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: casse-boubou/ha-addon-workflows/.github/workflows/pr-labels.yaml@adfb21c360f53273c5ad8e389f7e976a819d7e42 # main
