---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  workflows:
    uses: casse-boubou/ha-addon-workflows/.github/workflows/release-drafter.yaml@adfb21c360f53273c5ad8e389f7e976a819d7e42 # main
